/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactEntry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllNewsletterEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getContactInfo' : IDL.Func(
      [],
      [IDL.Record({ 'email' : IDL.Text, 'phone' : IDL.Text })],
      ['query'],
    ),
  'getUserContacts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ContactEntry)],
      ['query'],
    ),
  'submitContactEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactEntry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllNewsletterEmails' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getContactInfo' : IDL.Func(
        [],
        [IDL.Record({ 'email' : IDL.Text, 'phone' : IDL.Text })],
        ['query'],
      ),
    'getUserContacts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ContactEntry)],
        ['query'],
      ),
    'submitContactEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };